### ISSUE TITLE
panic during paho.mqtt.testing

### ISSUE THREAD

**Issue by liaoliaopro** [VolantMQ/volantmq#56]
run paho testing: python3 client_test.py
===========================

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc86c89]

goroutine 13 [running]:
github.com/VolantMQ/volantmq/topics/mem.subscriptionRecurseSearch(0x0, 0xc420776f30, 0x1, 0x1, 0xc42000e168)
	/home/bidong/.gvm/pkgsets/go1.9beta2/global/src/github.com/VolantMQ/volantmq/topics/mem/node.go:156 +0xa9
github.com/VolantMQ/volantmq/topics/mem.(*provider).subscriptionSearch(0xc420206480, 0xc420728ba0, 0x9, 0xc42000e168)
	/home/bidong/.gvm/pkgsets/go1.9beta2/global/src/github.com/VolantMQ/volantmq/topics/mem/node.go:178 +0x120
github.com/VolantMQ/volantmq/topics/mem.(*provider).publisher(0xc420206480)
	/home/bidong/.gvm/pkgsets/go1.9beta2/global/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:255 +0x40a
created by github.com/VolantMQ/volantmq/topics/mem.NewMemProvider
	/home/bidong/.gvm/pkgsets/go1.9beta2/global/src/github.com/VolantMQ/volantmq/topics/mem/topics.go:101 +0x966

**Comment by troian** [comment]
What test causes panic? I just run through few times and all them pass with no panics

**Comment by liaoliaopro** [comment]
Test with latest paho.mqtt.testing/interoperability

[volantmq_log.txt](https://github.com/VolantMQ/volantmq/files/1277221/volantmq_log.txt)

**Comment by troian** [comment]
Fixed int PR #57

**Comment by troian** [comment]
@liaoliaopro does this work on you side?

**Comment by liaoliaopro** [comment]
Tried example tcp,tcp&ws, still failed to pass test. log attatched below.

[volatmq_example_tcp&ws.txt](https://github.com/VolantMQ/volantmq/files/1279587/volatmq_example_tcp.ws.txt)
[volatmq_example_tcp.txt](https://github.com/VolantMQ/volantmq/files/1279588/volatmq_example_tcp.txt)

**Comment by liaoliaopro** [comment]
BTW, the panic is gone.

**Comment by liaoliaopro** [comment]
For exmaple tcp&ws, Ctrl-C cannot break it after paho testing.

**Comment by troian** [comment]
Close in favor of #58
